

# This file was *autogenerated* from the file ./solve.sage
from sage.all_cmdline import *   # import sage library

_sage_const_100 = Integer(100); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_200 = Integer(200)#!/usr/bin/env sage

N = _sage_const_100 
F = GF(_sage_const_2 )

with open('./output.txt', 'rb') as f:
    c = f.read()

origState = c[:_sage_const_200 ][::-_sage_const_1 ]
scdState = c[_sage_const_100 :_sage_const_200 ][::-_sage_const_1 ]

#mask = matrix([vector(F, 1) for i in range(N)])
mask = var('mask')
print mask

for i in range(N):
    state = origState[i:_sage_const_100 +i]
    state = matrix([int(c) for c in state])
    print state
    target = matrix([int(scdState[i])])
    print target
    desolve(state*mask==target, mask)


