

# This file was *autogenerated* from the file ./solve.sage
from sage.all_cmdline import *   # import sage library

_sage_const_4548674875 = Integer(4548674875); _sage_const_2 = Integer(2); _sage_const_1935961385155 = Integer(1935961385155); _sage_const_2854873820564 = Integer(2854873820564); _sage_const_1381088636252 = Integer(1381088636252); _sage_const_8353060610242 = Integer(8353060610242); _sage_const_353 = Integer(353); _sage_const_5636379357093 = Integer(5636379357093); _sage_const_15424654874903 = Integer(15424654874903); _sage_const_31617863 = Integer(31617863); _sage_const_9226233541419 = Integer(9226233541419); _sage_const_0 = Integer(0); _sage_const_16546484 = Integer(16546484); _sage_const_6860981508506 = Integer(6860981508506); _sage_const_6478678675 = Integer(6478678675); _sage_const_691 = Integer(691)#!/usr/bin/env sage
E = EllipticCurve(GF(_sage_const_15424654874903 ), [_sage_const_16546484 , _sage_const_4548674875 ])
print(E)
G = E(_sage_const_6478678675 , _sage_const_5636379357093 )
K = E(_sage_const_2854873820564 , _sage_const_9226233541419 )
C1 = E(_sage_const_6860981508506 , _sage_const_1381088636252 )
C2 = E(_sage_const_1935961385155 , _sage_const_8353060610242 )

#print(factor(E.order()))
primes = [_sage_const_2 , _sage_const_353 , _sage_const_691 , _sage_const_31617863 ]
dlogs = []
for fac in primes:
    t = int(G.order()) / int(fac)
    dlog = discrete_log(t*C2, t*G, operation="+")
    dlogs += [dlog]
r = crt(dlogs, primes)
print(r)
print(r*G == C2)

M = C1 - r*K
print(C1 == M+r*K)
x = M[_sage_const_0 ]
print(M == E.lift_x(x))
print(x)


