//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2020 Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t base64(int32_t a1);
int32_t rc4_1(bool a1, int32_t a2);
int32_t rc4_2(void);
int32_t rc4_3(void);
int32_t func(int32_t a1, int32_t a2);
int32_t check(int32_t * a1);

// --------------------- Global Variables ---------------------

int32_t g1 = 0; // a1
int32_t g2 = 0; // fp
int32_t g3 = 66;
char (*g4)[62] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
int32_t g5 = 0;
int32_t g6 = 0;
int32_t g7 = 0;
int32_t g8 = 0;
int32_t g9 = 0;
int32_t g10 = 0;
int32_t g11 = 0;
int32_t g12 = 0;
int32_t g13 = 0;
int32_t g14 = 0;
int32_t g15 = 0;
int32_t g16 = 0;
int32_t g17 = 0;
int32_t g18 = 0;
int32_t g19 = 0;
int32_t g20 = 0;
int32_t g21 = 0; // sp

// ------------------------ Functions -------------------------

// Address range: 0x4007a0 - 0x400ea4
int32_t base64(int32_t a1) {
    // 0x4007a0
    int32_t v1; // bp-80
    int32_t v2 = &v1; // 0x4007a0
    uint32_t v3 = (g5 - 1) * g5 % 2; // 0x4007c8
    int32_t v4; // 0x400818
    int32_t v5; // 0x400de4
    if (((int32_t)(v3 == 0) ^ (int32_t)(g10 < 10)) == 0) {
        // 0x400800
        if (((v3 || (int32_t)(g10 > 9)) ^ 1) == 0) {
            v5 = v2;
            goto lab_0x400de4;
        } else {
            v4 = v2;
            goto lab_0x400818;
        }
    } else {
        v4 = v2;
        goto lab_0x400818;
    }
  lab_0x400818:;
    int32_t v6 = v4 - 8; // 0x40081c
    int32_t v7 = v4 - 16; // 0x400828
    int32_t v8 = v4 - 40; // 0x40084c
    *(int32_t *)v6 = a1;
    *(int32_t *)(v8 - 8) = (int32_t)"/EXHYI6sc9RJPZyeqWi2QbNdh5uDL1MonwfS8VKxUrvF03lAGt7OgBk+zjC4Tmpa";
    int32_t v9 = v4 - 48; // 0x400884
    int32_t v10 = v4 - 24; // 0x400890
    int32_t v11 = v4 - 32; // 0x400894
    *(int32_t *)(v7 - 8) = strlen((char *)*(int32_t *)(v4 - 8));
    int32_t v12 = *(int32_t *)(v7 - 8); // 0x4008b0
    uint64_t v13 = 0x55555556 * (int64_t)v12; // 0x4008bc
    uint32_t v14 = (g5 - 1) * g5 % 2; // 0x4008f4
    int32_t v15 = g10 > 9; // 0x4008fc
    if ((v15 ^ v14) == 0) {
        // 0x400924
        if (((v14 || v15) ^ 1) == 0) {
            // 0x400924
            v5 = g21;
            goto lab_0x400de4;
        } else {
            goto lab_0x40093c;
        }
    } else {
        goto lab_0x40093c;
    }
  lab_0x400de4:;
    int32_t v16 = v5 - 40; // v1
    *(int32_t *)(v5 - 8) = a1;
    *(int32_t *)(v16 - 8) = (int32_t)"/EXHYI6sc9RJPZyeqWi2QbNdh5uDL1MonwfS8VKxUrvF03lAGt7OgBk+zjC4Tmpa";
    v1 = v5 - 16;
    int32_t len = strlen((char *)*(int32_t *)(v5 - 8)); // 0x400e50
    *(int32_t *)(v1 - 8) = len;
    v4 = g21;
    goto lab_0x400818;
  lab_0x40093c:;
    int32_t * v17 = (int32_t *)v10; // 0x40098c
    uint64_t v18 = 0x55555556 * (int64_t)*v17; // 0x400998
    int32_t v19 = 4 * ((int32_t)(v18 / 0x100000000) + (int32_t)(v18 / 0x8000000000000000)); // 0x4009a8
    if (v12 != 3 * ((int32_t)(v13 / 0x100000000) + (int32_t)(v13 / 0x8000000000000000))) {
        // 0x400988
        *(int32_t *)v7 = v19 + 4;
    } else {
        // 0x400954
        *(int32_t *)v7 = v19;
    }
    uint32_t v20 = (g5 - 1) * g5 % 2; // 0x4009d8
    int32_t * v21;
    int32_t * v22;
    if (((int32_t)(v20 == 0) ^ (int32_t)(g10 < 10)) == 0) {
        // 0x400a0c
        if (((v20 || (int32_t)(g10 > 9)) ^ 1) == 0) {
            // 0x400a0c
            v22 = (int32_t *)v8;
            v21 = (int32_t *)v11;
            goto lab_0x400e68;
        } else {
            goto lab_0x400a24;
        }
    } else {
        goto lab_0x400a24;
    }
  lab_0x400a24:;
    int32_t * v23 = (int32_t *)v11; // 0x400a28
    *v23 = 0;
    int32_t * v24 = (int32_t *)v8; // 0x400a30
    *v24 = 0;
    int32_t v25 = (g5 - 1) * g5 % 2 == 0; // 0x400a50
    int32_t v26 = g10 < 10; // 0x400a54
    if ((v25 & v26) == 0) {
        // 0x400a74
        if ((v25 ^ v26) == 0) {
            v22 = v24;
            v21 = v23;
            goto lab_0x400e68;
        } else {
            goto lab_0x400a94;
        }
    } else {
        goto lab_0x400a94;
    }
  lab_0x400a94:;
    int32_t * v27 = (int32_t *)v7; // 0x400aa0
    if (*v23 < *v27 - 2) {
        int32_t v28 = v9; // at
        v16 = v6;
        int32_t v29 = *v24 + *(int32_t *)v6; // 0x400ad4
        int32_t v30 = (int32_t)(*(char *)v29 / 4) + *(int32_t *)v9; // 0x400ae0
        int32_t v31 = v11; // a0
        int32_t v32 = &g20; // a3
        int32_t v33 = *v23 + (int32_t)&g20; // 0x400af8
        *(char *)v33 = *(char *)v30;
        int32_t v34 = v32 + *(int32_t *)v31; // 0x400b04
        int32_t v35 = *(int32_t *)v8 + *(int32_t *)v16; // 0x400b14
        int32_t v36 = 16 * ((int32_t)*(char *)v35 & -0xffffffd); // 0x400b2c
        int32_t v37 = (int32_t)(*(char *)(v35 + 1) / 16) | v36; // 0x400b40
        int32_t v38 = v37 + *(int32_t *)v28; // 0x400b44
        *(char *)(v34 + 1) = *(char *)v38;
        int32_t v39 = v32 + *(int32_t *)v31; // 0x400b54
        int32_t v40 = *(int32_t *)v16; // 0x400b5c
        int32_t v41 = *(int32_t *)v8; // 0x400b60
        int32_t v42 = (int32_t)*(char *)(v40 - (-1 - v41)); // 0x400b70
        int32_t v43 = 4 * ((v42 ^ 0x3ffffff0) & v42); // 0x400b84
        int32_t v44 = (int32_t)(*(char *)(v41 + v40 + 2) / 64); // 0x400b8c
        int32_t v45 = v44 & v43; // 0x400bc8
        int32_t v46 = v44 ^ -0x4f9376f2 ^ (v43 & 0x4f9376f0 | -1 - v43 & -0x4f9376f2) | v45; // 0x400bcc
        int32_t v47 = v46 + *(int32_t *)v28; // 0x400bd0
        *(char *)(v39 + 2) = *(char *)v47;
        int32_t v48 = v32 + *(int32_t *)v31; // 0x400be0
        int32_t v49 = *(int32_t *)v16 - (-2 - *(int32_t *)v8); // 0x400bf8
        int32_t v50 = (int32_t)*(char *)v49; // 0x400bfc
        int32_t v51 = ((v50 ^ -64) & v50) + *(int32_t *)v28; // 0x400c0c
        *(char *)(v48 + 3) = *(char *)v51;
        *v24 = *v24 + 3;
        *v23 = *v23 + 4;
        // 0x400abc
        while (*v23 < *v27 - 2) {
            // 0x400abc
            v28 = v9;
            v16 = v6;
            v29 = *v24 + *(int32_t *)v6;
            v30 = (int32_t)(*(char *)v29 / 4) + *(int32_t *)v9;
            v31 = v11;
            v32 = &g20;
            v33 = *v23 + (int32_t)&g20;
            *(char *)v33 = *(char *)v30;
            v34 = v32 + *(int32_t *)v31;
            v35 = *(int32_t *)v8 + *(int32_t *)v16;
            v36 = 16 * ((int32_t)*(char *)v35 & -0xffffffd);
            v37 = (int32_t)(*(char *)(v35 + 1) / 16) | v36;
            v38 = v37 + *(int32_t *)v28;
            *(char *)(v34 + 1) = *(char *)v38;
            v39 = v32 + *(int32_t *)v31;
            v40 = *(int32_t *)v16;
            v41 = *(int32_t *)v8;
            v42 = (int32_t)*(char *)(v40 - (-1 - v41));
            v43 = 4 * ((v42 ^ 0x3ffffff0) & v42);
            v44 = (int32_t)(*(char *)(v41 + v40 + 2) / 64);
            v45 = v44 & v43;
            v46 = v44 ^ -0x4f9376f2 ^ (v43 & 0x4f9376f0 | -1 - v43 & -0x4f9376f2) | v45;
            v47 = v46 + *(int32_t *)v28;
            *(char *)(v39 + 2) = *(char *)v47;
            v48 = v32 + *(int32_t *)v31;
            v49 = *(int32_t *)v16 - (-2 - *(int32_t *)v8);
            v50 = (int32_t)*(char *)v49;
            v51 = ((v50 ^ -64) & v50) + *(int32_t *)v28;
            *(char *)(v48 + 3) = *(char *)v51;
            *v24 = *v24 + 3;
            *v23 = *v23 + 4;
        }
    }
    int32_t v52 = *v17; // 0x400c64
    uint64_t v53 = 0x55555556 * (int64_t)v52; // 0x400c70
    int32_t v54 = (int32_t)(v53 / 0x100000000) + (int32_t)(v53 / 0x8000000000000000); // 0x400c7c
    int32_t result2 = -3 * v54 + v52; // 0x400c88
    if (result2 == 1) {
        // 0x400cbc
        *(char *)(*v23 + (int32_t)&g20 - 2) = 61;
        int32_t result = (int32_t)&g20 + *(int32_t *)v11; // 0x400cdc
        *(char *)(result - 1) = (char)61;
        // 0x400dcc
        return result;
    }
    // 0x400ca4
    if (result2 != 2) {
        // 0x400dcc
        return result2;
    }
    int32_t v55 = (g5 - 1) * g5 % 2 == 0; // 0x400d08
    int32_t v56 = g10 < 10; // 0x400d0c
    if ((v55 & v56) == 0) {
        // 0x400d2c
        if ((v55 ^ v56) == 0) {
            goto lab_0x400e80;
        } else {
            goto lab_0x400d44;
        }
    } else {
        goto lab_0x400d44;
    }
  lab_0x400e68:
    // 0x400e68
    *v21 = 0;
    *v22 = 0;
    goto lab_0x400a24;
  lab_0x400d44:
    // 0x400d44
    *(char *)(*v23 + (int32_t)&g20 - 1) = 61;
    uint32_t v57 = (g5 - 1) * g5 % 2; // 0x400d78
    int32_t result3 = (v57 | (int32_t)(g10 > 9)) ^ 1; // 0x400d94
    if (((int32_t)(v57 == 0) ^ (int32_t)(g10 < 10)) != 0 || result3 != 0) {
        // 0x400dcc
        return result3;
    }
    goto lab_0x400e80;
  lab_0x400e80:
    // 0x400e80
    *(char *)(*v23 + (int32_t)&g20 - 1) = 61;
    goto lab_0x400d44;
}

// Address range: 0x400ea4 - 0x400fec
int32_t rc4_1(bool a1, int32_t a2) {
    for (int32_t i = 0; i < 256; i++) {
        // 0x400ed4
        *(int32_t *)(4 * i + (int32_t)&g15) = i;
    }
    uint32_t v1 = (g11 - 1) * g11 % 2; // 0x400f20
    int32_t result = g6 > 9; // 0x400f30
    int32_t result2 = (v1 | result) ^ 1; // 0x400f3c
    if (v1 == 0 != g6 < 10) {
        // 0x400fd0
        return result;
    }
    if (result2 == 0) {
        while (true) {
            // continue -> 0x400fe4
        }
    }
    // 0x400fd0
    return result2;
}

// Address range: 0x400fec - 0x4014cc
int32_t rc4_2(void) {
    for (int32_t i = 0; i < 64; i++) {
        char v1 = *(char *)(*(int32_t *)&g4 + 63 - i); // 0x40103c
        *(int32_t *)(4 * i + (int32_t)&g17) = (int32_t)v1;
    }
    int32_t v2 = 0;
    uint32_t v3; // 0x401098
    int32_t v4; // 0x4010a8
    while (true) {
      lab_0x401080:
        // 0x401080
        v3 = (g12 - 1) * g12 % 2;
        int32_t v5 = v3 == 0; // 0x40109c
        int32_t v6 = g7 < 10; // 0x4010a0
        v4 = v5 ^ v6;
        if ((v5 & v6) == 0) {
            if (v4 == 0) {
                goto lab_0x4010d8;
            } else {
                goto lab_0x4010d8;
            }
        } else {
            goto lab_0x4010d8;
        }
    }
  lab_0x4011dc_2:;
    int32_t v7; // 0x4011f8
    int32_t v8; // 0x4011fc
    int32_t v9; // 0x401204
    int32_t v10; // 0x401240
    int32_t v11; // 0x401248
    int32_t v12; // 0x4013ec
    int32_t v13; // 0x4013f4
    while (true) {
        // 0x4011dc
        v7 = (v12 - 1) * v12 % 2 == 0;
        v8 = v13 < 10;
        v9 = v7 ^ v8;
        if ((v7 & v8) == 0) {
            if (v9 == 0) {
                goto lab_0x401234;
            } else {
                v11 = v13;
                v10 = v12;
                goto lab_0x401234;
            }
        } else {
            v11 = v13;
            v10 = v12;
            goto lab_0x401234;
        }
    }
  lab_0x4013e8:;
    int32_t v14; // 0x401444
    int32_t v15; // 0x40144421
    int32_t v16; // 0x40144c
    int32_t v17; // 0x40144c23
    if ((v7 & v8) == 0) {
        if (v9 == 0) {
            v17 = v13;
            v15 = v12;
            goto lab_0x4014c4;
        } else {
            v16 = v13;
            v14 = v12;
            goto lab_0x401440;
        }
    } else {
        v16 = v13;
        v14 = v12;
        goto lab_0x401440;
    }
  lab_0x401234:;
    uint32_t v18 = (v10 - 1) * v10 % 2; // 0x401254
    if (v18 == 0 == v11 < 10) {
        if ((v18 || (int32_t)(v11 > 9)) == 1) {
            goto lab_0x401234;
        } else {
            goto lab_0x4012a4;
        }
    } else {
        goto lab_0x4012a4;
    }
    goto lab_0x401234;
  lab_0x4012a4:;
    int32_t v19;
    if (v19 >= 256) {
        // break -> 0x4013e8
        goto lab_0x4013e8;
    }
    int32_t v20; // 0x401338
    int32_t v21; // 0x40133815
    int32_t v22; // 0x401340
    int32_t v23; // 0x40134017
    if ((v7 & v8) == 0) {
        if (v9 == 0) {
            v23 = v13;
            v21 = v12;
            goto lab_0x4014bc;
        } else {
            v22 = v13;
            v20 = v12;
            goto lab_0x401314;
        }
    } else {
        v22 = v13;
        v20 = v12;
        goto lab_0x401314;
    }
  lab_0x401314:;
    char * v24 = (char *)(v19 + (int32_t)&g16); // 0x401324
    if (((int32_t)((v20 - 1) * v20 % 2 == 0) & (int32_t)(v22 < 10)) == 0) {
        if ((v20 - 1) * v20 % 2 == 0 == v22 < 10) {
            v23 = v22;
            v21 = v20;
            goto lab_0x4014bc;
        } else {
            goto lab_0x401390;
        }
    } else {
        goto lab_0x401390;
    }
  lab_0x4014bc:
    v22 = v23;
    v20 = v21;
    goto lab_0x401314;
  lab_0x401390:;
    int32_t v25;
    int32_t v26;
    if (*v24 == 47) {
        // 0x4013a8
        *v24 = 0;
        v26 = g7;
        v25 = g12;
    } else {
        v26 = v13;
        v25 = v12;
    }
    // 0x4013d4
    v13 = v26;
    v12 = v25;
    v19++;
    // continue -> 0x4011dc
    goto lab_0x4011dc_2;
  lab_0x4010d8:
    if (v4 == 0) {
        if ((v3 || (int32_t)(g7 > 9)) == 1) {
            goto lab_0x4010d8;
        } else {
            goto lab_0x401148;
        }
    } else {
        goto lab_0x401148;
    }
  lab_0x401148:
    if (v2 >= 256) {
        v13 = g7;
        v12 = g12;
        v19 = 0;
        // break -> 0x4011dc
        goto lab_0x4011dc_2;
    }
    int32_t v27 = (int32_t)(-0x7df7df7d * (int64_t)v2 / 0x100000000) + v2; // 0x401174
    int32_t v28 = *(int32_t *)(4 * (-63 * (v27 / 32 + (int32_t)(v27 < 0)) + v2) + (int32_t)&g17); // 0x4011a0
    *(char *)(v2 + (int32_t)&g16) = (char)v28;
    v2++;
    goto lab_0x401080;
  lab_0x401440:;
    int32_t v29 = (v14 - 1) * v14 % 2 == 0; // 0x40145c
    int32_t result = v16 < 10; // 0x401460
    int32_t result2 = v29 ^ result; // 0x401468
    if ((v29 & result) != 0) {
        // 0x401498
        return result;
    }
    if (result2 != 0) {
        // 0x401498
        return result2;
    }
    v17 = v16;
    v15 = v14;
    goto lab_0x4014c4;
  lab_0x4014c4:
    v16 = v17;
    v14 = v15;
    goto lab_0x401440;
}

// Address range: 0x4014cc - 0x4015e0
int32_t rc4_3(void) {
    int32_t v1 = 0;
    int32_t * v2 = (int32_t *)(4 * v1 + (int32_t)&g15); // 0x401518
    char v3 = *(char *)(v1 + (int32_t)&g16); // 0x401538
    int32_t v4 = (int32_t)v3 + *v2;
    int32_t v5 = v4 - ((v4 >> 31) / 0x1000000 + v4 & -256); // 0x40155c
    int32_t v6 = 4 * v5; // 0x40157c
    *v2 = *(int32_t *)(v6 + (int32_t)&g15);
    int32_t result = (int32_t)&g15 + v6; // 0x4015a4
    *(int32_t *)result = *v2;
    while (v1 < 255) {
        // 0x401500
        v1++;
        v2 = (int32_t *)(4 * v1 + (int32_t)&g15);
        v3 = *(char *)(v1 + (int32_t)&g16);
        v4 = (int32_t)v3 + *v2 + v5;
        v5 = v4 - ((v4 >> 31) / 0x1000000 + v4 & -256);
        v6 = 4 * v5;
        *v2 = *(int32_t *)(v6 + (int32_t)&g15);
        result = (int32_t)&g15 + v6;
        *(int32_t *)result = *v2;
    }
    // 0x4015cc
    return result;
}

// Address range: 0x4015e0 - 0x401960
int32_t func(int32_t a1, int32_t a2) {
    // 0x4015e0
    int32_t v1; // bp-48
    int32_t v2 = &v1; // 0x4015e0
    uint32_t v3 = (g9 - 1) * g9 % 2; // 0x401604
    int32_t v4; // 0x401658
    int32_t v5; // 0x4018dc
    if (((int32_t)(v3 == 0) ^ (int32_t)(g14 < 10)) == 0) {
        // 0x401640
        if (((v3 || (int32_t)(g14 > 9)) ^ 1) == 0) {
            v5 = v2;
            goto lab_0x4018dc;
        } else {
            v4 = v2;
            goto lab_0x401658;
        }
    } else {
        v4 = v2;
        goto lab_0x401658;
    }
  lab_0x401658:;
    int32_t v6 = v4 - 8; // 0x40165c
    int32_t v7 = v4 - 16; // 0x401668
    int32_t v8 = v4 - 24; // 0x401674
    g1 = v8;
    int32_t v9 = v4 - 64; // t3
    *(int32_t *)v6 = a1;
    *(int32_t *)(v6 - 8) = a2;
    *(int32_t *)(v4 - 64) = 0;
    *(int32_t *)(v8 - 8) = 0;
    *(int32_t *)(v7 - 8) = 0;
    uint32_t v10 = (g9 - 1) * g9 % 2; // 0x4016ec
    int32_t v11 = v4 - 48; // 0x401714
    int32_t v12 = g1; // 0x401718
    int32_t v13 = v4 - 32; // 0x401720
    int32_t v14 = v4 - 40; // 0x401724
    if (((int32_t)(v10 == 0) ^ (int32_t)(g14 < 10)) == 0) {
        // 0x401738
        if (((v10 || (int32_t)(g14 > 9)) ^ 1) == 0) {
            // 0x401738
            v5 = g21;
            goto lab_0x4018dc;
        } else {
            goto lab_0x401758;
        }
    } else {
        goto lab_0x401758;
    }
  lab_0x4018dc:;
    int32_t v15 = v5 - 8; // 0x4018e0
    *(int32_t *)v15 = a1;
    *(int32_t *)(v15 - 8) = a2;
    *(int32_t *)(v5 - 64) = 0;
    *(int32_t *)(v5 - 32) = 0;
    *(int32_t *)(v5 - 24) = 0;
    v4 = g21;
    goto lab_0x401658;
  lab_0x401758:;
    int32_t * v16 = (int32_t *)v7; // 0x40175c
    int32_t v17 = *v16; // 0x40175c1
    *v16 = v17 - 1;
    if (v17 == 0) {
        // 0x4018c8
        return 0;
    }
    int32_t * v18 = (int32_t *)v12; // 0x40177c
    int32_t * v19 = (int32_t *)v13; // 0x4017a4
    int32_t v20 = *v18 + 1; // 0x401780
    int32_t v21 = -256; // a0
    *v18 = v20 - ((v20 >> 31) / 0x1000000 + v20 & -256);
    int32_t v22 = *(int32_t *)v12; // 0x4017a8
    int32_t v23 = &g15; // a2
    int32_t v24 = *(int32_t *)(4 * v22 + (int32_t)&g15) + *v19;
    *v19 = v24 - (v21 & (v24 >> 31) / 0x1000000 + v24);
    int32_t v25 = v23 + 4 * *(int32_t *)v12; // 0x4017f0
    g1 = v14;
    *(int32_t *)v14 = *(int32_t *)v25;
    int32_t v26 = v23; // 0x401808
    int32_t v27 = 4 * *(int32_t *)v12 + v26; // 0x401818
    *(int32_t *)v27 = *(int32_t *)(v26 + 4 * *(int32_t *)v13);
    int32_t v28 = v23 + 4 * *(int32_t *)v13; // 0x40182c
    *(int32_t *)v28 = *(int32_t *)g1;
    int32_t v29 = v23; // 0x40183c
    int32_t v30 = v29 + 4 * *(int32_t *)v12; // 0x40183c
    int32_t v31 = 4 * *(int32_t *)v13 + v29; // 0x40184c
    int32_t v32 = *(int32_t *)v31 + *(int32_t *)v30;
    *(int32_t *)v11 = v32 - ((v32 >> 31) / 0x1000000 + v32 & v21);
    int32_t v33 = v23 + 4 * *(int32_t *)v11; // 0x401884
    int32_t v34 = *(int32_t *)v9; // 0x401890
    int32_t v35 = 4 * v34 + (int32_t)&g18; // 0x4018a0
    *(int32_t *)v35 = *(int32_t *)v33;
    int32_t * v36 = (int32_t *)v9; // 0x4018a8
    *v36 = *v36 + 1;
    v1 = 0;
    int32_t v37 = *v16; // 0x40175c
    *v16 = v37 - 1;
    while (v37 != 0) {
        v20 = *v18 + 1;
        v21 = -256;
        *v18 = v20 - ((v20 >> 31) / 0x1000000 + v20 & -256);
        v22 = *(int32_t *)v12;
        v23 = &g15;
        v24 = *(int32_t *)(4 * v22 + (int32_t)&g15) + *v19;
        *v19 = v24 - (v21 & (v24 >> 31) / 0x1000000 + v24);
        v25 = v23 + 4 * *(int32_t *)v12;
        g1 = v14;
        *(int32_t *)v14 = *(int32_t *)v25;
        v26 = v23;
        v27 = 4 * *(int32_t *)v12 + v26;
        *(int32_t *)v27 = *(int32_t *)(v26 + 4 * *(int32_t *)v13);
        v28 = v23 + 4 * *(int32_t *)v13;
        *(int32_t *)v28 = *(int32_t *)g1;
        v29 = v23;
        v30 = v29 + 4 * *(int32_t *)v12;
        v31 = 4 * *(int32_t *)v13 + v29;
        v32 = *(int32_t *)v31 + *(int32_t *)v30;
        *(int32_t *)v11 = v32 - ((v32 >> 31) / 0x1000000 + v32 & v21);
        v33 = v23 + 4 * *(int32_t *)v11;
        v34 = *(int32_t *)v9;
        v35 = 4 * v34 + (int32_t)&g18;
        *(int32_t *)v35 = *(int32_t *)v33;
        v36 = (int32_t *)v9;
        *v36 = *v36 + 1;
        v1 = 0;
        v37 = *v16;
        *v16 = v37 - 1;
    }
    // 0x4018c8
    return 0;
}

// Address range: 0x401960 - 0x401fa8
int32_t check(int32_t * a1) {
    int32_t str = (int32_t)a1; // 0x401970
    int32_t v1; // bp-200
    int32_t v2 = &v1; // 0x401984
    memcpy(&v1, &g3, 176);
    if (strlen((char *)str) != 44) {
        // 0x401f0c
        return 0;
    }
    uint32_t v3 = (g8 - 1) * g8 % 2; // 0x4019e8
    int32_t v4 = g13 < 10; // 0x4019f0
    int32_t v5; // 0x401a38
    int32_t v6; // 0x401f2c
    int32_t v7; // 0x401a38
    int32_t v8; // 0x401a98
    if (v3 == 0 == g13 < 10) {
        if ((v3 || (int32_t)(g13 > 9)) == 1) {
            v8 = 9;
            v6 = v4;
            goto lab_0x401f28;
        } else {
            v7 = 9;
            v5 = v4;
            goto lab_0x401a34;
        }
    } else {
        v7 = 9;
        v5 = v4;
        goto lab_0x401a34;
    }
  lab_0x401e88:;
    int32_t v9; // 0x401e8c
    int32_t v10; // 0x401e8c24
    int32_t v11; // 0x401e94
    int32_t v12; // 0x401e9426
    if (((int32_t)((v9 - 1) * v9 % 2 == 0) & (int32_t)(v11 < 10)) == 0) {
        if ((v9 - 1) * v9 % 2 == 0 == v11 < 10) {
            v12 = v11;
            v10 = v9;
            goto lab_0x401fa0;
        } else {
            goto lab_0x401ee8;
        }
    } else {
        goto lab_0x401ee8;
    }
  lab_0x401fa0:
    v11 = v12;
    v9 = v10;
    goto lab_0x401e88;
  lab_0x401ee8:;
    // 0x401ee8
    int32_t v13;
    int32_t v14 = v13 + 1; // 0x401eec
    int32_t result;
    if (v14 >= 44) {
        result = 1;
        goto lab_0x401f0c;
    }
    int32_t v15 = v11; // 0x401e30
    int32_t v16 = v9; // 0x401e28
    v13 = v14;
    goto lab_0x401de4;
  lab_0x401b34:;
    // 0x401b34
    int32_t v19; // 0x401b44
    int32_t v20; // 0x401b448
    int32_t v21; // 0x401b4c
    int32_t v22; // 0x401b4c10
    if (((int32_t)((v19 - 1) * v19 % 2 == 0) & (int32_t)(v21 < 10)) == 0) {
        if ((v19 - 1) * v19 % 2 == 0 == v21 < 10) {
            v22 = v21;
            v20 = v19;
            goto lab_0x401f78;
        } else {
            goto lab_0x401b9c;
        }
    } else {
        goto lab_0x401b9c;
    }
  lab_0x401f78:
    v21 = v22;
    v19 = v20;
    goto lab_0x401b34;
  lab_0x401b9c:;
    int32_t v23;
    if (v23 >= 44) {
        // break -> 0x401cfc
        goto lab_0x401cfc;
    }
    int32_t v24 = *(int32_t *)(4 * v23 + (int32_t)&g18); // 0x401bc8
    unsigned char v25 = *(char *)(v23 + str); // 0x401bd4
    *(char *)(v23 + (int32_t)&g19) = (char)(v24 ^ (int32_t)v25);
    uint32_t v26 = (g8 - 1) * g8 % 2; // 0x401c3c
    int32_t v27 = g13 > 9; // 0x401c44
    int32_t v28;
    if (v27 == v26) {
        if ((v26 || v27) == 1) {
            // 0x401f80
            v28 = v23 + 1;
            goto lab_0x401c80;
        } else {
            v28 = v23;
            goto lab_0x401c80;
        }
    } else {
        v28 = v23;
        goto lab_0x401c80;
    }
  lab_0x401c80:;
    int32_t v29 = v28 + 1; // 0x401c90
    int32_t v30; // 0x401d00
    int32_t v31; // 0x401d08
    if (((int32_t)(v26 == 0) & (int32_t)(g13 < 10)) != 0) {
        v31 = g13;
        v30 = g8;
        v23 = v29;
        // continue -> 0x401adc
        goto lab_0x401adc_3;
    }
    if (v26 == 0 != g13 < 10) {
        v31 = g13;
        v30 = g8;
        v23 = v29;
        // continue -> 0x401adc
        goto lab_0x401adc_3;
    }
    // 0x401f80
    v28 = v29 + 1;
    goto lab_0x401c80;
  lab_0x401a34:
    // 0x401a34
    rc4_1(v5 % 2 != 0, v7);
    rc4_2();
    rc4_3();
    func(str, 44);
    printf("========================:\n ");
    int32_t v32 = (g8 - 1) * g8 % 2 == 0; // 0x401a94
    v8 = g13 < 10;
    if ((v32 & v8) == 0) {
        if ((v32 ^ v8) == 0) {
            v6 = 0;
            goto lab_0x401f28;
        } else {
            v31 = g13;
            v30 = g8;
            v23 = 0;
            goto lab_0x401adc_3;
        }
    } else {
        v31 = g13;
        v30 = g8;
        v23 = 0;
        goto lab_0x401adc_3;
    }
  lab_0x401f28:
    // 0x401f28
    rc4_1(v6 != 0, v8);
    rc4_2();
    rc4_3();
    func(str, 44);
    printf("========================:\n ");
    v7 = g1;
    v5 = (int32_t)"========================:\n ";
    goto lab_0x401a34;
  lab_0x401adc_3:;
    uint32_t v33; // 0x401af4
    while (true) {
        // 0x401adc
        v33 = (v30 - 1) * v30 % 2;
        if (((int32_t)(v33 == 0) & (int32_t)(v31 < 10)) == 0) {
            if (v33 == 0 == v31 < 10) {
                v22 = v31;
                v20 = v30;
                goto lab_0x401f78;
            } else {
                v21 = v31;
                v19 = v30;
                goto lab_0x401b34;
            }
        } else {
            v21 = v31;
            v19 = v30;
            goto lab_0x401b34;
        }
    }
  lab_0x401cfc:;
    int32_t v34 = v31 > 9; // 0x401d1c
    int32_t v35; // 0x401d60
    int32_t v36; // 0x401d6018
    int32_t v37; // 0x401d68
    int32_t v38; // 0x401d6820
    if (v33 == v34) {
        if ((v33 || v34) == 1) {
            v38 = v31;
            v36 = v30;
            goto lab_0x401f94;
        } else {
            v37 = v31;
            v35 = v30;
            goto lab_0x401d58;
        }
    } else {
        v37 = v31;
        v35 = v30;
        goto lab_0x401d58;
    }
  lab_0x401d58:;
    uint32_t v39 = (v35 - 1) * v35 % 2; // 0x401d74
    if (v39 == 0 == v37 < 10) {
        if ((v39 || (int32_t)(v37 > 9)) == 1) {
            v38 = v37;
            v36 = v35;
            goto lab_0x401f94;
        } else {
            goto lab_0x401dc8;
        }
    } else {
        goto lab_0x401dc8;
    }
  lab_0x401f94:
    v37 = v38;
    v35 = v36;
    goto lab_0x401d58;
  lab_0x401dc8:
    v15 = v31;
    v16 = v30;
    v13 = 0;
    while (true) {
      lab_0x401de4:;
        char v17 = *(char *)(v13 + (int32_t)&g19); // 0x401df4
        if ((int32_t)v17 != *(int32_t *)(4 * v13 + v2)) {
            result = 0;
            // break -> 0x401f0c
            break;
        }
        uint32_t v18 = (v16 - 1) * v16 % 2; // 0x401e3c
        if (v18 == 0 == v15 < 10) {
            if ((v18 || (int32_t)(v15 > 9)) == 1) {
                v12 = v15;
                v10 = v16;
                goto lab_0x401fa0;
            } else {
                v11 = v15;
                v9 = v16;
                goto lab_0x401e88;
            }
        } else {
            v11 = v15;
            v9 = v16;
            goto lab_0x401e88;
        }
    }
  lab_0x401f0c:
    // 0x401f0c
    return result;
}

// Address range: 0x401fa8 - 0x40207c
int main(int argc, char ** argv) {
    // 0x401fa8
    int32_t v1; // bp-96
    g2 = &v1;
    int32_t v2; // bp-52
    scanf("%s", &v2);
    base64((int32_t)&v2);
    if (check(&g20) == 1) {
        // 0x402028
        printf("good job boy\n");
    } else {
        // 0x402044
        printf("try it again\n");
    }
    // 0x402060
    return 0;
}

// --------------- Dynamically Linked Functions ---------------

// void * memcpy(void * restrict dest, const void * restrict src, size_t n);
// int printf(const char * restrict format, ...);
// int scanf(const char * restrict format, ...);
// size_t strlen(const char * s);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.4.0)
// Detected functions: 7
// Decompilation date: 2020-01-01 17:52:46
